[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "module_olist"
version = "0.0.1"
description = "Brazilian e-commerce public dataset"
authors = [
  { name = "yanchagas04" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "fg-data-profiling>=4.19.1",
    "ipython",
    "ipywidgets>=8.1.8",
    "jupyterlab",
    "lightgbm>=4.7.0",
    "loguru",
    "matplotlib",
    "mkdocs",
    "notebook",
    "numpy",
    "pandas",
    "pandera>=0.32.1",
    "pip",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "seaborn>=0.13.2",
    "setuptools==81.0.0",
    "tqdm",
    "typer",
    "xgboost>=3.4.1",
]
requires-python = "==3.12.13"


[tool.ruff]
line-length = 99
src = ["module_olist"]
include = ["pyproject.toml", "module_olist/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["module_olist"]
force-sort-within-sections = true

